<a href="https://colab.research.google.com/github/santhi1712/python_work/blob/main/numpywork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [ ]:
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)#bytes of ecah elments of the array
print(a.size)
print(type(a))
print(a.data)

2
int64
8
15
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array([2, 3, 4])
print(a)
#2 dimen array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
# we can specify type of array explictly
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
np.empty((2,3),dtype=np.int32)#initial contect is random and depends on state of memmory

array([[2, 0, 3],
       [0, 4, 0]], dtype=int32)

In [ ]:
#create sequence of numbers
np.arange(10,30,5)#with fiffrence 5
np.linspace(0,4,9)#9 numbers from 0 to 2


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
b = np.arange(24).reshape(3,2,4)     # 2d array
print(b)



In [ ]:
#basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a-b:",a-b)
print(b**2)
print(a<40)

a-b: [20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [ ]:
A = np.array([[1, 1],[0, 1]])#2D
B = np.array([[2, 0],[3, 4]])
print(A * B)    # elementwise product

print(A @ B)     # matrix product #[[1*2+1*3, 1*0+1*4],[0*2+1*3, 0*0+1*4]]

print(A.dot(B))  # another matrix product


In [ ]:
a=np.array([0,1,2])#1d
b=np.array([2,3,4])
print(a.dot(b))

11


In [ ]:
a = np.array([13,14,60])
print(a)
print(a.sum())
print(a.min())
print(a.max())


[13 14 60]
87
13
60


In [ ]:
num=np.arange(12).reshape(3,4)
print(num)
print(num.sum(axis=0))#sum of each co
print(num.sum(axis=1))#sum of each row
print(num.cumsum(axis=1))#cumilative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [ ]:
#indexing,slicing and iterating
s = np.arange(10)**3
print(s)
print(s[3])
print(s[2:6])
print(s[:6:2])#give every alternate(skips 2 nd element)
print(s[:6:3])#(skips 3 rd element)
print(s[::-1])#reverse of s

[  0   1   8  27  64 125 216 343 512 729]
27
[  8  27  64 125]
[ 0  8 64]
[ 0 27]
[729 512 343 216 125  64  27   8   1   0]


In [ ]:
def f(x, y):
    return 10 * x + y
num=np.fromfunction(f,(5,4),dtype=int)
print(num)
print(num[2,3]) #3rd column,2nd element
print(num[0:5,1])#each row in second column
print(num[:,1])#same as above
print(num[1:3,:])#exclude outer limit,so 1,2 row taken
print(num[-1])#last row
#iterating over multi dimensional array
for row in num:
  print(row)
#iterates each elemnet through flat
for element in num.flat:
  print(element)

In [ ]:
f=np.array([[1,2,3,4],[3,5,6,7],[10,11,2,4],[3,6,7,8],[12,8,9,51]])
print(f.shape)
print(f.ravel()) #flatten array
print(f.reshape(4,5))#returns the array with modified shape
print(f.T) #TRANSPOSE
print(f.T.shape)
#f.reshape(2,10)
f.resize(4,5) #modifies the array itself
f.shape
print(f)
print(f.reshape(5,-1))#if -1 given it will calculate dimensions autmatically
f.shape

In [ ]:
#copies and views
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(a)
b=a #no new object created ;2 names for same array
print(b)
print(b is a)

#shallow copy(kind of view)
c=a.view()
print(c)
print(c is a)
print(c.base is a)
print(c.flags.owndata)
c=c.reshape(2,6)# a's shape wont chnage
print(c.shape)
print(a.shape)
c[0,3]=1234 #it changes a data also
print(c)
print(a)

#Deep copy
d = a.copy() # a new array object with new data creted
print( d is a)
d[0,1]=9999
print(a) #not effected a
print(d)

In [ ]:
m= np.arange(12).reshape(3, 4)
print(m)
n=a>8
print(n)
print(m[n])
m[n]=0
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False  True]
 [False False False False]
 [False  True  True  True]]
[ 3  9 10 11]
[[0 1 2 0]
 [4 5 6 7]
 [8 0 0 0]]


In [ ]:
#second way of boolen indexing
a = np.arange(9).reshape(3,3)
print(a)
b1 = np.array([False, True, True])         # first dim selection
b2 = np.array([True, False, True,])  # second dim selection
print(a[b1])
print(a[:,b2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]]
[[0 2]
 [3 5]
 [6 8]]


In [ ]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a, b, c) #ix_ function can be used to combine different vectors so as to obtain the result for each n-uplet.
print(ax)
print(ax.shape)
print(bx.shape)
print(a[3] + b[2] * c[4])


[[[2]]

 [[3]]

 [[4]]

 [[5]]]
(4, 1, 1)
(1, 3, 1)
17


In [1]:
result=ax+bx*cx
print(result)
print(result[3,0,3])#3rd array,0th row,3rd column element

NameError: ignored