<a href="https://colab.research.google.com/github/santhi1712/python_work/blob/main/numpywork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [10]:
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)#bytes of ecah elments of the array
print(a.size)
print(type(a))
print(a.data)

2
int64
8
15
<class 'numpy.ndarray'>


In [14]:
import numpy as np
a = np.array([2, 3, 4])
print(a)
#2 dimen array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
# we can specify type of array explictly
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
