<a href="https://colab.research.google.com/github/santhi1712/python_work/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as  np
al=np.arange(10)
print(al)
al2=np.arange(0,10,2)#craetes a range with step 2
print(al2)
az=np.zeros(4)#craetes an array with all 0's
print(az)
print(al2.shape)
az2=np.zeros((2,4))#creates a two dimensional array with 2 rows and 3 cols
print(az2.shape)
a5 = np.full((2,3), 8) # array of rank 2 with all 8s
print(a5)

In [ ]:
import numpy as  np
a6 = np.eye(4) # 4x4 identity matrix
print(a6)

In [ ]:
#create an array with randon numbers
a7 = np.random.random((2,4)) # rank 2 array (2 rows 4 columns) with
print(a7)


In [ ]:
#create numpy array from list
list1 = [1,2,3,4,5]
list2 = [7,8,9,10,11]
r1 = np.array(list1) # rank 1 array
print(r1)
print(r1[1])
r2=np.array([list1,list2])
print(r2)
print(r2.shape)
print(r2[0,1])
print(r2[[1,1]])#use list as index

In [ ]:
#slicing arrays
a = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print(a)
b1=a[1:3,:3] # row 1 to 3 (not inclusive) and first 3 columns
print(b1)
b2 = a[-2:,-2:]
print(b2)
b1[0,2]=10 # when changing reference array element the mail array element is also reflect that change
print("b1",b1)
print(a)#element 10 i schanges as per above

In [ ]:
#array math
x1=np.array([[1,2,3],[8,9,10]])
y1=np.array([[4,2,6],[5,2,8]])
print(x1+y1)
print(np.add(x1,y1))#same as + for add
print(x1-y1)#np.subtract(x1,y1)
print(x1*y1)#np.multiply(x1,y1)
print(x1/y1)#np.divide(x1,y1)

In [ ]:
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])
bmi = weights/heights **2 # calculate the BMI
print(bmi)
print("Overweight: " , names[bmi>25])
# Overweight: ['Ann']
print("Underweight: " , names[bmi<18.5])
# Underweight: ['Joe']
print("Healthy: " , names[(bmi>=18.5) & (bmi<=25)])
# Healthy: ['Mark']


In [ ]:
#dot product
x = np.array([2,3])
y = np.array([4,2])
print(np.dot(x,y)) # 2x4 + 3x2 = 14
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10], [11,12]])
print(np.dot(x2,y2)) # matrix multiplication


In [60]:
#matrix is strictly 2 dimensional while ndarray is multi dimensional
x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print(x2*y2)#it is a dot matrix where as for arrays it is element by elemnt
x1=np.array([[1,2],[3,4]])
print(x1)
x3=np.asmatrix(x1)#convert numpy array into matrix
print(x3)

[[11 14]
 [38 47]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [65]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)
print(a.cumsum())#print the culmilative sum of elemnts in array
print(a.cumsum(axis=1)) # sum over columns for each of the 3 rows
print(a.cumsum(axis=0)) # sum over columns for each of the 3 rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [67]:
#numpy sorting
age=np.array([30,23,10,21,4])
sorted_age=np.sort(age)
print(sorted_age)
print(np.argsort(age))#returns the indices of elements


[ 4 10 21 23 30]
[4 2 3 1 0]


In [69]:
 persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
 ages = np.array([34,12,37,5,13])
 heights = np.array([1.76,1.2,1.68,0.5,1.25])
 sort_indices=np.argsort(ages)
 reverse_sort_indices=np.argsort(ages)[::-1]#reverse the order of list
 #so based on sort_indices it will get the results below
 print(persons[sort_indices])
 print(heights[sort_indices])
 print(persons[reverse_sort_indices])
 print(heights[reverse_sort_indices])

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[0.5  1.2  1.25 1.76 1.68]
['Peter' 'Johnny' 'Joe' 'Mary' 'Will']
[1.68 1.76 1.25 1.2  0.5 ]


In [75]:
#craete a copy of array
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
print(a1)
a2=a1
print(a2)
a2[0][0]=50#changes made to a2 effects a1 as well
print(a2)
print(a1)
a1.shape=1,-1
print(a1)
print(a2)
a2=a1.view()#creates a copy of a1 by reference but changes in dimension in a1 not effect a2
print(a2)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[50  2  3  4]
 [ 5  6  7  8]]
[[50  2  3  4]
 [ 5  6  7  8]]
[[50  2  3  4  5  6  7  8]]
[[50  2  3  4  5  6  7  8]]
[[50  2  3  4  5  6  7  8]]
