<a href="https://colab.research.google.com/github/santhi1712/python_work/blob/main/numpywork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [10]:
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)#bytes of ecah elments of the array
print(a.size)
print(type(a))
print(a.data)

2
int64
8
15
<class 'numpy.ndarray'>


In [14]:
import numpy as np
a = np.array([2, 3, 4])
print(a)
#2 dimen array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
# we can specify type of array explictly
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [22]:
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
np.empty((2,3),dtype=np.int32)#initial contect is random and depends on state of memmory

array([[2, 0, 3],
       [0, 4, 0]], dtype=int32)

In [24]:
#create sequence of numbers
np.arange(10,30,5)#with fiffrence 5
np.linspace(0,4,9)#9 numbers from 0 to 2


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
b = np.arange(24).reshape(3,2,4)     # 2d array
print(b)



In [33]:
#basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a-b:",a-b)
print(b**2)
print(a<40)

a-b: [20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [ ]:
A = np.array([[1, 1],[0, 1]])#2D
B = np.array([[2, 0],[3, 4]])
print(A * B)    # elementwise product

print(A @ B)     # matrix product #[[1*2+1*3, 1*0+1*4],[0*2+1*3, 0*0+1*4]]

print(A.dot(B))  # another matrix product


In [36]:
a=np.array([0,1,2])#1d
b=np.array([2,3,4])
print(a.dot(b))

11


In [41]:
a = np.array([13,14,60])
print(a)
print(a.sum())
print(a.min())
print(a.max())


[13 14 60]
87
13
60


In [46]:
num=np.arange(12).reshape(3,4)
print(num)
print(num.sum(axis=0))#sum of each co
print(num.sum(axis=1))#sum of each row
print(num.cumsum(axis=1))#cumilative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [49]:
#indexing,slicing and iterating
s = np.arange(10)**3
print(s)
print(s[3])
print(s[2:6])

[  0   1   8  27  64 125 216 343 512 729]
27
[  8  27  64 125]
